
/**
* Generator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Generator.idl
* środa, 28 grudnia 2016 10:10:39 CET
*/

public interface Generator extends GeneratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Generator
