
/**
* Generator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Generator.idl
* czwartek, 5 stycznia 2017 23:36:28 CET
*/

public interface Generator extends GeneratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Generator
